Please add Burrow
essentialkaos/kaos-repo pull request #192
Opened 2018-07-23 19:37 UTC by kulikovav

Burrow is a kafka consumer lag checker

2018-07-23 21:44 UTC, andyone requested changes

2018-07-23 21:44 UTC, andyone commented on specs/Burrow.spec
> +Requires:        golang
This tool requires `golang` for usage?

2018-07-23 21:44 UTC, andyone commented on specs/Burrow.spec
> +go get -v github.com/linkedin/%{name}
You download the latest version of sources from GitHub. It means build isn't reproducible and it's not a 1.1.0 release at all.

You can add `rpmbuilder` tag for creating source archive with all dependencies using `gopack`. There is the [example](https://github.com/essentialkaos/kaos-repo/blob/master/specs/etcd.spec#L3) from another golang application spec file.

2018-07-23 21:44 UTC, andyone commented on specs/Burrow.spec
> +install -pm 755 src/github.com/linkedin/%{name}/%{name} \
I think you should change the name from `Burrow` to `burrow`. Using capital letters in names is discouraged.

2018-07-23 21:44 UTC, andyone commented on specs/Burrow.spec
> +Summary:         Burrow - Kafka Consumer Lag Checking
Application name shouldn't be a part of the summary.

2018-07-24 07:29 UTC, kulikovav commented
Thanks, Anton! I updated the spec file. Could you please take a look on it. Now I get a warning from rpmlint about invalid source. Do I need to do something with that or it is fine?

2018-07-24 09:29 UTC, andyone commented
> Now I get a warning from rpmlint about invalid source. Do I need to do something with that or it is fine?

It's ok. I highly recommend using [this](https://github.com/essentialkaos/perfecto/blob/master/common/rpmlint.conf) rpmlint config, with disabled useless warnings. Or use [this](https://hub.docker.com/r/essentialkaos/perfecto/tags/) docker image with _perfecto_, where this config already used.

2018-07-24 09:31 UTC, andyone approved these changes

2018-07-24 09:33 UTC, andyone commented
Looks good for me now. Merged.

2018-07-24 09:34 UTC, merged

2018-07-24 09:46 UTC, andyone commented
@kulikovav `Burrow-1.1.0` has been added to `kaos-testing` repository.