Add Haproxy Dataplane API
essentialkaos/kaos-repo pull request #234
Opened 2020-03-05 21:42 UTC by kulikovav

### What's this PR about
Data Plane API is a sidecar process that runs next to HAProxy and provides API endpoints for managing HAProxy. 
It requires HAProxy version 1.9.0 or higher.

### TODO's:

- [ ] Run [`perfecto`](https://github.com/essentialkaos/perfecto) check on your spec file
- [ ] Write [`bibop`](https://github.com/essentialkaos/bibop) tests
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**Did you try to build the package with this spec?:** No
**Is this ready for review?:** No

2020-03-08 00:16 UTC, andyone requested changes

2020-03-08 00:16 UTC, andyone commented on specs/dataplaneapi/dataplaneapi.spec
> +  %{__sysctl} daemon-reload &>/dev/null || :
Useless spaces at the beginning of the line.

2020-03-08 00:16 UTC, andyone commented on specs/dataplaneapi/dataplaneapi.spec
> +BuildRequires:      golang >= 1.12
It is better to use the latest version of go for the build. The latest available version in the release repository is 1.13.7.

2020-03-08 00:16 UTC, andyone commented on tests/dataplaneapi.recipe
> +command "systemctl start {service_name}" "Start dataplaneapi daemon"
If version specific tools are used for the test (_like systemd in this case, which available on CentOS/RHEL >= 7_), you should add the version to file suffix. The proper name for the file will be `dataplaneapi-c7.recipe`

2020-03-08 00:16 UTC, andyone commented on specs/dataplaneapi/dataplaneapi.spec
> +%global crc_check pushd ../SOURCES ; sha512sum -c %{SOURCE100} ; popd
Macro for [automatic CRC generation and check](https://github.com/essentialkaos/rpmbuilder/wiki/Automatic-SHA-512-checksum-generation) defined but there is no `Source100` or macro usage.

2020-03-10 07:55 UTC, kulikovav commented
Such a horrible PR. @andyone, thank you for review. I made the changes.

2020-03-10 11:55 UTC, andyone approved these changes

2020-03-10 11:56 UTC, andyone commented
Looks good, merged.

2020-03-10 11:56 UTC, merged

2020-03-10 21:27 UTC, andyone commented
The package was built and added to `kaos-testing` repository.