Remove the alerting patch. Use ClickHouse built-in plugins backend instead.
essentialkaos/kaos-repo pull request #243
Opened 2020-09-16 14:06 UTC by gongled

### What's this PR about

This PR removes the maintained patch that has provided alerting engine support for the "ClickHouse" data source in favor of the built-in plugin backend from Vertamedia.

Fortunately, it is not necessary to adapt the following patch in every Grafana's upgrade. Now Grafana 7+ supports new backend API that is using to run 3rd-party server-side plugins (written in Go), not only on the user-side. 

So, we can nice and easy prune the implementation of the same functionality from the core forever. Is it great, isn't it?

### TODO's:

- [ ] Run [`perfecto`](https://github.com/essentialkaos/perfecto) check on your spec file
- [ ] Write [`bibop`](https://github.com/essentialkaos/bibop) tests
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**Did you try to build the package with this spec?:** Yes
**Is this ready for review?:** No

2020-09-18 12:53 UTC, andyone requested changes

2020-09-18 12:53 UTC, andyone commented on specs/grafana-plugin-clickhouse-datasource.spec
> +Release:              1%{?dist}
I think we should not bump the package release. It still in the testing repo, so we can just replace the previously built version.

2020-09-28 12:25 UTC, andyone commented
@gongled Hi! Do you have any ETA for this PR?

2020-09-29 10:37 UTC, gongled commented
@andyone sorry for delay. I've reverted `%{dist}` macro changes.

2020-09-29 14:52 UTC, andyone commented
Ouch! Looks like the latest version of bibop is broken. I'll try to fix it ASAP. Pay no attention to build status.

2020-09-30 12:56 UTC, andyone requested changes

2020-09-30 12:56 UTC, andyone commented on specs/grafana/grafana.spec
> +* Wed Sep 16 2020 Gleb Goncharov <g.goncharov@fun-box.ru> - 7.1.5-1
Changelog still contains info about release 1.

2020-09-30 12:56 UTC, andyone commented on specs/grafana-plugin-clickhouse-datasource.spec
> +Release:              1%{?dist}
This release bump also should be reveted.

2020-10-02 07:15 UTC, gongled commented on specs/grafana/grafana.spec
> +* Wed Sep 16 2020 Gleb Goncharov <g.goncharov@fun-box.ru> - 7.1.5-1
Fixed (28e9f58)

2020-10-02 09:15 UTC, andyone requested changes

2020-10-02 09:15 UTC, andyone commented on specs/grafana-plugin-clickhouse-datasource.spec
> +Release:              1%{?dist}
☝️

2020-12-10 10:33 UTC, andyone commented
@gongled Hi! Is there any plans with this PR?

2020-12-10 15:09 UTC, closed without merging