Update Kafka to 2.7.0
essentialkaos/kaos-repo pull request #253
Opened 2021-02-15 17:56 UTC by gongled

### What's this PR about

I've updated Kafka to 2.7.0. Nothing special here.

### Known build problems and traps

None.

### TODO's:

- [x] Run [`perfecto`](https://github.com/essentialkaos/perfecto) check on your spec file
- [ ] Write [`bibop`](https://github.com/essentialkaos/bibop) tests
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**Did you try to build the package with this spec?:** Yes
**Is this ready for review?:** Yes

2021-02-25 11:27 UTC, andyone requested changes

2021-02-25 11:27 UTC, andyone commented on specs/kafka/SOURCES/checksum.sha512
> +ea0522ed4bcc7648c6a22b0fb14d54ef63acf9c0bbcdbb6d8e26904270e4718cba0a7ceabd1b325183157cc978bea9e40d76824ae034ca00b82178ad1cd1b128  2.7.0.tar.gz
@gongled `checksum.sha512` is not required for the build process. This file automatically generated by `rpmbuilder` while building packages. Also, this spec doesn't have a macro for checking these checksums.

2021-03-20 19:06 UTC, andyone commented
@gongled Hi! I hope you doing well. Is there any news about this PR?

2021-03-22 08:46 UTC, andyone commented
> Files changed: 236

😱

2021-03-22 08:58 UTC, gongled commented
@andyone, I removed `checksum.sha512` file. Is there anything else which I can help you with?

2021-03-22 09:11 UTC, andyone commented
@gongled I can't merge this PR because it changes a lot of files.

2021-03-22 18:21 UTC, gongled commented
> @gongled I can't merge this PR because it changes a lot of files.

I understand. I do not know what happened. I will create yet another pull request properly soon.

2021-03-22 18:21 UTC, closed without merging