Update Gradle to 6.8.2
essentialkaos/kaos-repo pull request #254
Opened 2021-02-15 17:59 UTC by gongled

### What's this PR about

I've updated Gradle to 6.8.2 to be able to update Kafka to 2.7.0.

### Known build problems and traps

None.

### TODO's:

- [x] Run [`perfecto`](https://github.com/essentialkaos/perfecto) check on your spec file
- [ ] Write [`bibop`](https://github.com/essentialkaos/bibop) tests
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**Did you try to build the package with this spec?:** Yes
**Is this ready for review?:** Yes

2021-02-25 11:31 UTC, andyone requested changes

2021-02-25 11:31 UTC, andyone commented on specs/gradle/SOURCES/checksum.sha512
> +885961b001fdfe221511f66d81f2962adffa6d3a5fd8148dd20591e8ff2222135216fb67fffa4248c814b4e059097f2b767c7e023b6249fbf36d558bf3674b61  gradle-6.8.2-src.zip
`checksum.sha512` is not required for the build process. This file automatically generated by `rpmbuilder` while building packages. Also, this spec doesn't have a macro for checking these checksums.

2021-02-25 11:31 UTC, andyone commented on specs/gradle/gradle.spec
> +BuildRequires:        jdk13 git
We don't longer provide non-LTS packages with Java. Currently, the repository contains only JDK8 and JDK11 packages.

2021-03-20 19:06 UTC, andyone commented
@gongled Hi! I hope you doing well. Is there any news about this PR?

2021-03-22 08:34 UTC, gongled commented
> @gongled Hi! I hope you doing well. Is there any news about this PR?

I removed `checksum.sha512` file, but I do not drop JDK version to LTS version. Unfortunately, Gradle 6.8.2 can be only build using JDK 13. Also, Gradle 6.8.x is required to build Kafka 2.7.0 (https://github.com/essentialkaos/kaos-repo/pull/253).

Do you have any ideas how can I improve this RPM spec?

2021-03-22 08:41 UTC, andyone commented
> Unfortunately, Gradle 6.8.2 can be only build using JDK 13.

We use packages with AdoptOpenJDK binaries. Currently, [there is no JDK 12-15](https://adoptopenjdk.net/index.html).

2021-03-22 08:44 UTC, andyone commented
> Currently, there is no JDK 12-15.

I was wrong; these versions in the archive. But I dropped them due to a lack of time for supporting and updating non-LTS versions.

2021-03-22 18:37 UTC, gongled commented
OK. It comes across as there is no chance to get this merged. Closed.

2021-03-22 18:37 UTC, closed without merging